# -*- coding: utf-8 -*-
"""RePose: Real-Time Pose Estimation & Motion Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMzPU8PgKEostEThgMmUS1kHAGsdnvW8
"""

!pip install opencv-python matplotlib

!pip install kaggle

!kaggle datasets download -d hanumanthuarya/human-pose-10-activity-video-dataset

!unzip human-pose-10-activity-video-dataset.zip

import os
os.listdir()

import os

folder = "walk/walk"
videos = os.listdir(folder)

video_path = os.path.join(folder, videos[43])
print(video_path)

!apt-get install ffmpeg -y

!ffmpeg -i "walk/walk/American_History_X_walk_f_nm_np1_ba_med_13.avi" output.mp4 -y

video_path = "output.mp4"

import cv2

cap = cv2.VideoCapture(video_path)
print("Opened:", cap.isOpened())

!pip install mediapipe==0.10.21

import cv2
import mediapipe as mp
import matplotlib.pyplot as plt

mp_pose = mp.solutions.pose
mp_drawing = mp.solutions.drawing_utils

cap = cv2.VideoCapture("output.mp4")

with mp_pose.Pose() as pose:
    ret, frame = cap.read()

    image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = pose.process(image)

    if results.pose_landmarks:
        mp_drawing.draw_landmarks(
            frame,
            results.pose_landmarks,
            mp_pose.POSE_CONNECTIONS
        )

cap.release()

plt.imshow(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
plt.axis('off')

keypoints = []
cap = cv2.VideoCapture("output.mp4")

with mp_pose.Pose() as pose:
    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        results = pose.process(image)

        if results.pose_landmarks:
            frame_kp = []
            for lm in results.pose_landmarks.landmark:
                frame_kp.append([lm.x, lm.y, lm.z])
            keypoints.append(frame_kp)

cap.release()

import numpy as np
keypoints = np.array(keypoints)
print(keypoints.shape)

def calculate_angle(a, b, c):
    a, b, c = np.array(a), np.array(b), np.array(c)
    ba = a - b
    bc = c - b

    angle = np.arccos(
        np.dot(ba, bc) / (np.linalg.norm(ba) * np.linalg.norm(bc))
    )
    return np.degrees(angle)

angles_left = []
angles_right = []

for frame in keypoints:
    # LEFT
    angles_left.append(calculate_angle(frame[23], frame[25], frame[27]))

    # RIGHT
    angles_right.append(calculate_angle(frame[24], frame[26], frame[28]))

import matplotlib.pyplot as plt

plt.plot(angles_left, label="Left Knee")
plt.plot(angles_right, label="Right Knee")
plt.legend()
plt.title("Knee Angles Over Time")

import numpy as np

def smooth(signal, window=7):
    return np.convolve(signal, np.ones(window)/window, mode='valid')

smooth_left = smooth(angles_left)
smooth_right = smooth(angles_right)

import matplotlib.pyplot as plt

plt.plot(smooth_left, label="Left Knee (Smoothed)")
plt.plot(smooth_right, label="Right Knee (Smoothed)")
plt.legend()
plt.title("Smoothed Knee Angles")

symmetry = np.abs(np.array(smooth_left) - np.array(smooth_right))

plt.plot(symmetry)
plt.title("Left vs Right Knee Symmetry")

velocity = np.diff(keypoints[:,25,:], axis=0)  # left knee
speed = np.linalg.norm(velocity, axis=1)

plt.plot(speed)
plt.title("Knee Velocity")

